apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms1
  template:
    metadata:
      labels:
        app: ms1
    spec:
      containers:
        - name: ms1
          image: dockersrana/ms1:1
