apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms1
  template:
    metadata:
      labels:
        app: ms1
    spec:
      containers:
        - name: ms1
          image: dockersrana/ms1:1
---
apiVersion: v1
kind: Service
metadata:
  name: ms1-srv
spec:
  selector:
    app: ms1
  ports:
    - name: ms1
      protocol: TCP
      port: 4000
      targetPort: 4000
