apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms2-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms2
  template:
    metadata:
      labels:
        app: ms2
    spec:
      containers:
        - name: ms2
          image: dockersrana/ms2:2
---
apiVersion: v1
kind: Service
metadata:
  name: ms2-srv
spec:
  selector:
    app: ms2
  ports:
    - name: ms2
      protocol: TCP
      port: 4000
      targetPort: 4000
